"""
Define the list of possible commands that TeX might handle. These commands
might be composed of multiple instructions, such as 'input', which requires
characters forming a file-name as an argument.
"""
from enum import Enum


class Commands(Enum):
    assign = 'ASSIGN'
    relax = 'RELAX'
    left_brace = 'LEFT_BRACE'
    right_brace = 'RIGHT_BRACE'
    begin_group = 'BEGIN_GROUP'
    end_group = 'END_GROUP'
    show_token = 'SHOW_TOKEN'
    show_box = 'SHOW_BOX'
    show_lists = 'SHOW_LISTS'
    show_the = 'SHOW_THE'
    ship_out = 'SHIP_OUT'
    ignore_spaces = 'IGNORE_SPACES'
    set_after_assignment_token = 'SET_AFTER_ASSIGNMENT_TOKEN'
    add_to_after_group_tokens = 'ADD_TO_AFTER_GROUP_TOKENS'
    message = 'MESSAGE'
    error_message = 'ERROR_MESSAGE'
    open_input = 'OPEN_INPUT'
    close_input = 'CLOSE_INPUT'
    open_output = 'OPEN_OUTPUT'
    close_output = 'CLOSE_OUTPUT'
    write = 'WRITE'
    do_special = 'DO_SPECIAL'
    add_penalty = 'ADD_PENALTY'
    add_kern = 'ADD_KERN'
    add_math_kern = 'ADD_MATH_KERN'
    un_penalty = 'UN_PENALTY'
    un_kern = 'UN_KERN'
    un_glue = 'UN_GLUE'
    mark = 'MARK'
    insert = 'INSERT'
    vertical_adjust = 'VERTICAL_ADJUST'
    add_leaders = 'ADD_LEADERS'
    add_space = 'ADD_SPACE'
    add_box = 'ADD_BOX'
    unpack_horizontal_box = 'UNPACK_HORIZONTAL_BOX'
    unpack_vertical_box = 'UNPACK_VERTICAL_BOX'
    indent = 'INDENT'
    no_indent = 'NO_INDENT'
    par = 'PAR'
    add_horizontal_glue = 'ADD_HORIZONTAL_GLUE'
    add_vertical_glue = 'ADD_VERTICAL_GLUE'
    move_box_left = 'MOVE_BOX_LEFT'
    move_box_right = 'MOVE_BOX_RIGHT'
    raise_box = 'RAISE_BOX'
    lower_box = 'LOWER_BOX'
    add_horizontal_rule = 'ADD_HORIZONTAL_RULE'
    add_vertical_rule = 'ADD_VERTICAL_RULE'
    horizontal_align = 'HORIZONTAL_ALIGN'
    vertical_align = 'VERTICAL_ALIGN'
    end = 'END'
    dump = 'DUMP'
    add_control_space = 'CONTROL_SPACE'
    add_character_explicit = 'ADD_CHARACTER_EXPLICIT'
    add_character_code = 'ADD_CHARACTER_CODE'
    add_character_token = 'ADD_CHARACTER_TOKEN'
    add_accent = 'ADD_ACCENT'
    add_italic_correction = 'ADD_ITALIC_CORRECTION'
    add_discretionary = 'ADD_DISCRETIONARY'
    add_discretionary_hyphen = 'ADD_DISCRETIONARY_HYPHEN'
    do_math_shift = 'DO_MATH_SHIFT'
