from ..constants.instructions import (Instructions as I,
                                      message_instructions,
                                      hyphenation_instructions,
                                      register_instructions,
                                      h_add_glue_instructions,
                                      v_add_glue_instructions,
                                      short_hand_def_instructions,
                                      def_instructions,
                                      if_instructions
                                      )
from ..tokens import instructions_to_types

base_terminal_instructions = (
    I.box_dimen_height,
    I.box_dimen_width,
    I.box_dimen_depth,
    I.less_than,
    I.greater_than,
    I.equals,
    I.plus_sign,
    I.minus_sign,
    I.zero,
    I.one,
    I.two,
    I.three,
    I.four,
    I.five,
    I.six,
    I.seven,
    I.eight,
    I.nine,
    I.single_quote,
    I.double_quote,
    I.backtick,
    I.point,
    I.comma,
    I.a,
    I.b,
    I.c,
    I.d,
    I.e,
    I.f,
    I.space,
    I.misc_char_cat_pair,
    I.integer_parameter,
    I.dimen_parameter,
    I.glue_parameter,
    I.mu_glue_parameter,
    I.token_parameter,
    I.special_integer,
    I.special_dimen,

    I.char_def_token,
    I.math_char_def_token,
    I.count_def_token,
    I.dimen_def_token,
    I.skip_def_token,
    I.mu_skip_def_token,
    I.toks_def_token,
    I.unexpanded_control_symbol,
    I.accent,

    I.cat_code,
    I.math_code,
    I.upper_case_code,
    I.lower_case_code,
    I.space_factor_code,
    I.delimiter_code,
    I.let,
    I.advance,
    I.par,
    I.relax,
    I.immediate,
    I.font,
    I.skew_char,
    I.hyphen_char,
    # I.font_dimen,
    I.text_font,
    I.script_font,
    I.script_script_font,
    # I.undefined,
    I.global_mod,
    I.long_mod,
    I.outer_mod,
    I.set_box,
    I.box,
    I.copy,
    I.un_h_box,
    I.un_h_copy,
    I.un_v_box,
    I.un_v_copy,
    # I.last_box,
    # I.v_split,
    # I.box_dimen_height,
    # I.box_dimen_width,
    # I.box_dimen_depth,
    I.kern,
    I.math_kern,
    I.v_rule,
    I.h_rule,
    I.input,
    I.ship_out,
    I.end,
    I.char,
    I.indent,
    I.left_brace,
    I.right_brace,
    I.font_def_token,
    I.arbitrary_token,
    I.parameter_text,
    I.balanced_text_and_right_brace,
    I.horizontal_mode_material_and_right_brace,
    I.vertical_mode_material_and_right_brace,
    I.h_box,
    I.v_box,
    I.v_top,
    I.active_character,
    I.unexpanded_control_word,
    I.after_assignment,
    I.after_group,
    I.non_active_uncased_a,
    I.non_active_uncased_b,
    I.non_active_uncased_c,
    I.non_active_uncased_d,
    I.non_active_uncased_e,
    I.non_active_uncased_f,
    I.non_active_uncased_g,
    I.non_active_uncased_h,
    I.non_active_uncased_i,
    I.non_active_uncased_j,
    I.non_active_uncased_k,
    I.non_active_uncased_l,
    I.non_active_uncased_m,
    I.non_active_uncased_n,
    I.non_active_uncased_o,
    I.non_active_uncased_p,
    I.non_active_uncased_q,
    I.non_active_uncased_r,
    I.non_active_uncased_s,
    I.non_active_uncased_t,
    I.non_active_uncased_u,
    I.non_active_uncased_v,
    I.non_active_uncased_w,
    I.non_active_uncased_x,
    I.non_active_uncased_y,
    I.non_active_uncased_z,
)
terminal_instructions = (
    base_terminal_instructions
    + register_instructions
    + message_instructions
    + hyphenation_instructions
    + h_add_glue_instructions
    + v_add_glue_instructions
    + short_hand_def_instructions
    + def_instructions
    + if_instructions
)
terminal_types = instructions_to_types(terminal_instructions)
